### PR TITLE
change nested loop order

### PR DESCRIPTION
**Pull request by psychocoderHPC**
change fast moving rows to columns for nested loops

The array's in pngwriter is created out of Y (rows) and X (columns). A image consists of Y pointers to a pointer. Each row is a one dimensional array of X elements.
To move cache efficient over this data structure the inner loop of a nested loop must move over the columns.

### CODE REVIEW

**Comment by psychocoderHPC** [comment]
This change should also speedup all changed loops.

**Comment by ax3l** [comment]
very nice, related to #47

**Comment by ax3l** [comment]
@psychocoderHPC After testing the PR against `dev` with 1e4 x 1e4 images in `tests/performance.cc` I could not see any change in runtime that is significant.

**Comment by ax3l** [comment]
[cachegrind]() results with 1e3 x 1e3 and `-DCMAKE_BUILD_TYPE=Debug`:

```bash
valgrind --tool=cachegrind ./performance
```

`dev`:
```
==9398== I   refs:      1,906,281,408
==9398== I1  misses:            2,694
==9398== LLi misses:            2,648
==9398== I1  miss rate:          0.00%
==9398== LLi miss rate:          0.00%
==9398== 
==9398== D   refs:        670,606,725  (499,507,669 rd   + 171,099,056 wr)
==9398== D1  misses:       16,141,278  ( 13,841,881 rd   +   2,299,397 wr)
==9398== LLd misses:          273,662  (     92,919 rd   +     180,743 wr)
==9398== D1  miss rate:           2.4% (        2.7%     +         1.3%  )
==9398== LLd miss rate:           0.0% (        0.0%     +         0.1%  )
==9398== 
==9398== LL refs:          16,143,972  ( 13,844,575 rd   +   2,299,397 wr)
==9398== LL misses:           276,310  (     95,567 rd   +     180,743 wr)
==9398== LL miss rate:            0.0% (        0.0%     +         0.1%  )
```

`PR`:
```
==9756== I   refs:      1,904,148,979
==9756== I1  misses:            2,683
==9756== LLi misses:            2,639
==9756== I1  miss rate:          0.00%
==9756== LLi miss rate:          0.00%
==9756== 
==9756== D   refs:        668,802,714  (498,223,366 rd   + 170,579,348 wr)
==9756== D1  misses:       16,220,232  ( 13,925,788 rd   +   2,294,444 wr)
==9756== LLd misses:          273,662  (     92,919 rd   +     180,743 wr)
==9756== D1  miss rate:           2.4% (        2.7%     +         1.3%  )
==9756== LLd miss rate:           0.0% (        0.0%     +         0.1%  )
==9756== 
==9756== LL refs:          16,222,915  ( 13,928,471 rd   +   2,294,444 wr)
==9756== LL misses:           276,301  (     95,558 rd   +     180,743 wr)
==9756== LL miss rate:            0.0% (        0.0%     +         0.1%  )
```

**Comment by psychocoderHPC** [comment]
I updated the performance test (pull request is coming soon):

results with 1e4 x 1e4 and -DCMAKE_BUILD_TYPE=Release / **all times are micro sec**
dev:
```
allocation time: 292 140
random value time: 4 930 386
png copy (in RAM) time: 4 527 704
png scale_k(0.5) time: 5 709 906
png scale_k(2.0) time: 111 012 900
write_png() time: 42 972 140
```

pull request:
```
allocation time: 287 672
random value time: 4 990 129
png copy (in RAM) time: 1 297 697
png scale_k(0.5) time: 4 014 548
png scale_k(2.0) time: 64 083 936
write_png() time: 43 124 053
```

**Comment by ax3l** [comment]
ok looks decent on scaling and copy time. Would be cool if we could target `write_png` itself, too.

**Pull request merged**
