### PR TITLE
automatic deletion of trailing whitespaces by SciTE

### PR DESCRIPTION
**Pull request by mxmlnkn**
Just to show you how many white space errors there are. This makes contributing difficult for me and maybe others.

### CODE REVIEW

**Comment by mxmlnkn** [comment]
Btw: there also is a steady mix of tabs and spaces. Moreover the tab size used to write this doesn't seem to be 4 spaces.

**Comment by ax3l** [comment]
this breaks the historic beauty of the project by renovating it instead of restoring it ;)

We can update the spaces and tabs but then we should
- commit under a generic user (because you use a tool for it and `git blame` will credit nearly all lines of the project to you): `GIT_AUTHOR_NAME="Tools" GIT_AUTHOR_EMAIL="tools@example.com" git [...]`
- only use 4 spaces (exception: `Makefile`s need Tabs...)
- fix all places where indentation is now wrong
- think of a way to prevent new tabs from coming into the project in future PRs again (e.g., travis checks)

**Comment by ax3l** [comment]
we can start with trailing white spaces in in PR, but pls commit under a generic user (simple tool/script usage).

also: please document the script and command options you used to make the change in the PR description. :+1:

**Comment by ax3l** [comment]
since the branch is out of date I will fix the trailing white spaces in a separate PR!
we should take care of the tabs in yet an other PR later on.

**Pull request closed without merging**
