### PR TITLE
try different paths for burro.png, especially to support cmake build inside ./build/ folder

### PR DESCRIPTION
**Pull request by mxmlnkn**

### CODE REVIEW

**Comment by ax3l** [comment]
That "try more paths" change looks a bit random to me.

Builds should all be done out-of-source and if the file is then missing for the test CMake should copy it for us.

**Comment by ax3l** [comment]
What is the build command you used and what did not work as expected?

(try to use a short, distinct title in issues/PRs and a on-the-point description :) )

**Comment by mxmlnkn** [comment]
mkdir build
    cd build
    cmake ..
    make
    ./pngtest
    
and I get:

    Generating one.png... done. Writing to disk... done.
    Generating two.png... done. Writing to disk... done.
    Opening burro.png... PNGwriter::readfromfile - ERROR **: Error opening file "burro.png".
     PNGwriter::readfromfile - ERROR **: No such file or directory
     done.
    The image that has just been read from disk (burro.png) is 1 pixels high and 1 pixels wide.
    Bit depth is 16
    Image gamma is: 0.6
    Writing to disk... done.

**Comment by ax3l** [comment]
I will fix this after lunch, had a similar task in libSplash in the past.

**Comment by ax3l** [comment]
Will be fixed in #96.

**Pull request closed without merging**
